datahes:
	@echo "====> Building hes data"
	go build -v golang.gurusys.co.uk/go-clients/data/hes
getter:
	@echo "====>  Building getter"
	go build -v golang.gurusys.co.uk/go-clients/getter
hes-client:
	@echo "====> Building hes-client"
	go install golang.gurusys.co.uk/go-clients/hes-client/main.go

all:	hes-client
